name: ${name}
version: ${version}
description: ${description}
authors: ${authors}
website: ${url}

main: ${mainClass}
api-version: ${apiVersion}
softdepend: [ CoreProtect ]
commands:
  msdecor:
    usage: " ꀑ §cИспользуй: /<command> [параметры]"
    permission: msDecor.msdecor
    description: Прочья хуйня
permissions:
  msdecor.*:
    default: op
    children:
      msDecor.msdecor: true
  msDecor.msdecor:
    default: op
